### ISSUE TITLE
Cannot install react native 56 update : using react-native init

### ISSUE THREAD

**Issue by ankitjpk** [react-native-community/react-native-releases#36]
Hey, 
Congrats for the new release.
WE just been waiting for the new release and unfortunately am not able take up your update.

import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Module._compile (F:\Users\nw\Work\ReactNative\newapps\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:646:10)
    at Object.newLoader [as .js] (F:\Users\nw\Work\ReactNative\newapps\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

**Comment by johakr** [comment]
https://github.com/facebook/react-native/issues/20015#issuecomment-402968028

**Comment by kelset** [comment]
This is not the right repository to write this kind of issues too. Thanks @johakr for the link.

**Comment by skptricks** [comment]
You need to switch back to old version by using following commands : 
react-native init MobileApp --version react-native@0.55.4
